name: /DATA2025/cjh/envs/IRL
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cffi=1.17.0=py38heb5c249_0
  - click=8.1.7=unix_pyh707e725_0
  - docker-pycreds=0.4.0=py_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libabseil=20240116.2=cxx17_he02047a_1
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libprotobuf=4.25.3=hd5b35b9_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - psutil=6.0.0=py38hfb59056_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h4a871b0_2_cpython
  - python_abi=3.8=8_cp38
  - readline=8.2=h8c095d6_2
  - sentry-sdk=2.19.2=pyhd8ed1ab_0
  - setproctitle=1.3.3=py38h01eb140_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.2.0
      - easydict==1.13
      - einops==0.8.1
      - filelock==3.16.1
      - flatbuffers==25.9.23
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - gast==0.4.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - keras==2.13.1
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - metric-learn==0.7.0
      - networkx==3.1
      - numpy==1.24.3
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.0.3
      - pathtools==0.1.2
      - pillow==10.4.0
      - pip==25.0.1
      - prettytable==3.11.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - requests==2.32.4
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - setuptools==75.3.2
      - six==1.17.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.22
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tornado==6.4.2
      - tqdm==4.67.1
      - typing-extensions==4.5.0
      - tzdata==2025.2
      - visdom==0.2.4
      - wandb==0.15.12
      - wcwidth==0.2.14
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - wrapt==2.0.1
      - yacs==0.1.8
      - zipp==3.20.2
prefix: /DATA2025/cjh/envs/IRL
