wandb_version: 1

batch_size:
  desc: null
  value: 128
workers:
  desc: null
  value: 8
height:
  desc: null
  value: 256
width:
  desc: null
  value: 128
num_instances:
  desc: null
  value: 4
MODEL:
  desc: null
  value: 50x
optimizer:
  desc: null
  value: SGD
lr:
  desc: null
  value: 0.008
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0001
warmup_step:
  desc: null
  value: 10
milestones:
  desc: null
  value:
  - 30
resume:
  desc: null
  value: ''
evaluate:
  desc: null
  value: false
epochs0:
  desc: null
  value: 80
epochs:
  desc: null
  value: 60
eval_epoch:
  desc: null
  value: 100
seed:
  desc: null
  value: 0
print_freq:
  desc: null
  value: 200
data_dir:
  desc: null
  value: /DATA2025/cjh/AAAI2025-LReID-DASK/PRID
logs_dir:
  desc: null
  value: /DATA2025/cjh/AAAI2025-LReID-DASK/output
config_file:
  desc: null
  value: config/base.yml
test_folder:
  desc: null
  value: null
setting:
  desc: null
  value: 3
middle_test:
  desc: null
  value: true
AF_weight:
  desc: null
  value: 1.0
fix_EMA:
  desc: null
  value: 0.5
global_alpha:
  desc: null
  value: 100
absolute_feat:
  desc: null
  value: false
save_evaluation:
  desc: null
  value: false
absolute_delta:
  desc: null
  value: true
trans:
  desc: null
  value: true
random_rehearser:
  desc: null
  value: false
blur:
  desc: null
  value: false
n_kernel:
  desc: null
  value: 1
groups:
  desc: null
  value: 1
joint_test:
  desc: null
  value: false
mobile:
  desc: null
  value: true
aux_weight:
  desc: null
  value: 4.5
dropout:
  desc: null
  value: 0.5
l2sp_weight:
  desc: null
  value: 0.01
fisher_freeze:
  desc: null
  value: true
fisher_ratio:
  desc: null
  value: 0.5
fisher_sample_num:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1765768290.066306
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 79
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      - 79
      3:
      - 13
      - 16
      - 23
      4: 3.8.20
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
